### ISSUE TITLE
Use sosa:resultTime/sosa:phenomenonTime instead of time:hasTime

### ISSUE THREAD

**Issue by nicholascar** [AGLDWG/phs-ont#12]
From @dr-shorthair 's initial review

**Comment by F3RR3T** [comment]
This issue and others should autoclose on review of forthcoming pull-request from cox-review branch.

**Comment by F3RR3T** [comment]
I think I took "sosa:resultTime/sosa:phenomenonTime" literally.
When i use this string as a restriction, Protege parses it as:
    
    sosa:phenomenonTime exactly 1 time:TemporalEntity

What I really want is the RESULT time, the (date|time) at which the observation was conducted. We would probably like to know `sosa:phenomonTime` (how long the pest has been lurking around) but this is a hidden variable.

**Comment by dr-shorthair** [comment]
Result time  is when the result became available - e.g. when it was inserted in the database
Phenomenon time is the time associated with the thing in the world - e.g. when the observer looked at the thing.

**Comment by F3RR3T** [comment]
Ok thanks!. Will set the property back to phenomenonTime

The descriptions at https://www.w3.org/TR/vocab-ssn/#SOSAphenomenonTime
are a bit ambiguous:
> result time - The result time is the instant of time when the Observation, Actuation or Sampling activity was completed.

> phenomenon time - The time that the Result of an Observation, Actuation, or Sampling applies to the FeatureOfInterest. 

The example for `Result` talks about a tree being 20m tall. Based on that, given that the tree has been that size ever since it grew that high, the time period of the phenomenon would have to be an estimate (e.g. 2 months, a year?). I suppose a more amenable example would be checking a rain gauge. I make the observation at 9am, but it has been raining since 9am yesterday. So I would have thought the phenomenonTime would be the 24 time period and resultTime would be the time I checked the gauge.

An aside:
This second example (rain gauge) is relevant to insect trapping. When statisticians work on trap catches, they want to know how long the trap was set. Was it 1 hour or 2 weeks? We accommodate this attribute by recording surveillance 'Effort'. I have recently modelled this as a Feature Of Interest. The units of 'Effort' vary according to the type of surveillance. Therefore we have a Vocabulary for Units of Effort, with allowed units matched to InspectionMethod (Procedures).  I was contemplating modelling `phs:Effort` as phenomenonTime, but I think FoI works.

In any case, we are iterating towards a much better shape.
