### ISSUE TITLE
Superclass of Host

### ISSUE THREAD

**Issue by dr-shorthair** [AGLDWG/phs-ont#13]
Should be union-of dwc:Taxon and :Stratum - i.e. OR, not AND.

**Comment by dr-shorthair** [comment]
Else I'm not understanding what a 'Stratum' is - I only know it in context of vegetation surveys, though I'm aware the term is also used in statistical sampling.

**Comment by F3RR3T** [comment]
The intention behind the superclass 'Stratum' was to define the 'thing' on which a pest was found. Surveillance observations either record the "Host" (usually a plant) or the 'Substrate' (non-living material, eg a rock). So, 'Host' should be a subclass of Taxon and of 'Stratum'.
See  http://linked.data.gov.au/def/phs#Stratum
I chose 'Stratum' for its root meaning of 'layer', something on which something else could rest, But since 'Stratum' usually has a geological meaning, maybe we can find a better word?
Note that I called it an 'abstract' class, by which I meant that no instance data will ever use it in its range.

**Comment by dr-shorthair** [comment]
Stratum is probably OK in this context. But I was trying to understand if the combination of super-classes was what you intended. As currently axiomatized, every Host is **both** a Taxon and a Stratum. I'm not sure that was what you intended. If you want every Host to be **either** a Taxon and a Stratum then the super-class must be a union-class. 

Separately, I also think you've got Taxon wrong - see #18

**Comment by F3RR3T** [comment]
We are now modelling `Host` and `Substrate` as subclasses of `sosa:Platform`.

The fact that a host is a living organism is secondary to its primary role, which is the thing on which a target pest may be resting.

> Platform - A Platform is an entity that hosts other entities, particularly Sensors, Actuators, Samplers, and other Platforms.
