### ISSUE TITLE
Sub-classes of Taxon

### ISSUE THREAD

**Issue by dr-shorthair** [AGLDWG/phs-ont#18]
:`Host`. `:Plant`, `:Sample Animal` are all shown as subclass of `dwc:Taxon`. 
I don't think this is right. 'Taxon' is a classification, associated with an Occurrence, but individuals are not usually modelled as instances of a Taxon. I think they are all sub-classes of `dwc:Occurrence`. An Occurrence is [associated with](https://dwc.tdwg.org/terms/#dwc:associatedTaxa) one or more taxa.

**Comment by dr-shorthair** [comment]
See https://dwc.tdwg.org/terms/#occurrence and https://dwc.tdwg.org/terms/#taxon

**Comment by dr-shorthair** [comment]
Related - the range of the properties `catchesPest` and `detectsPest` might be Taxon. 
It might be worth looking at the [System Capabiliities](https://www.w3.org/TR/vocab-ssn/#System-capabilities) module of SSN to see if these capabilities fit there.

**Comment by F3RR3T** [comment]
I see your distinction between 'taxon' as a classification and 'occurrence', a statement about the 'status' of a taxon associated with an observation.
However, I believe I am correctly considering `:Pest` and `:Host` as subclasses of `:Taxon`.
For example, we are interested in some insect that we consider a Pest, regardless of whether it is present and before we have even gone out to look for it. Thus, `catchesPest` and `detectsPest` are correctly associated with `:Taxon` as a superclass of `:Pest`.

`:SampleAnimal` should be be an occurrence. However, this element has been renamed (in Bracng 'Pest', for which I'll submit a pull request shortly,  since it it inaccurate.

However, we should clearly record that

**Comment by dr-shorthair** [comment]
`Pest` and `Host` are _roles_ of an organism in a particular context. You could model that as sub-classes of Taxon, but I suspect that is not the best way to do it.

**Comment by F3RR3T** [comment]
I have renamed `SampleAnimal` to `TargetPestGroup`, and removed it as a subclass of `dwc:Taxon`. So this is partially fixed.
`Plant` should be deleted altogether I think
`Host` still needs attention.

**Comment by F3RR3T** [comment]
> Related - the range of the properties `catchesPest` and `detectsPest` might be Taxon.
> It might be worth looking at the [System Capabiliities](https://www.w3.org/TR/vocab-ssn/#System-capabilities) module of SSN to see if these capabilities fit there.

The range of all the `<verb>Pest` object properties is now `TargetPestGroup`.

**Comment by F3RR3T** [comment]
I think I have solved the `:Host` problem. Modelling it as a sosa:Platform. It just happens to be a living plant.
I've also deleted `:Plant`, since it appears to serve no purpose.
Next merge will close this issue.
